cache: bundler
sudo: false
bundler_args: ""
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
script: "bundle exec rake spec"
matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/rails32.gemfile
