cache: bundler
sudo: false
bundler_args: ""
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
branches:
  only: master
script: "bundle exec rake spec"
matrix:
  exclude:
    - rvm: 2.3.4
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails4.2.gemfile
